### ISSUE TITLE
Домашка №0, которую и так все сделали

### ISSUE THREAD

**Issue by tiny-kottan** [YanaPlotnyk/kottans-js-2016#1]
1. Установить git / ознакомиться с ним
2. IDE/editor, ознакомиться с ним.
3. DevTools - пройти на CodeSchool (http://discover-devtools.codeschool.com/).
4. Github - завести репозитарий для домашек.
5. GitBranching: http://pcottle.github.io/learnGitBranching/ пройти Main, забросить скриншот в гитхаб, сюда запостить ссылку

**Comment by YanaPlotnyk** [comment]
kottans-js-2016/gitbranching.jpg

**Comment by sudodoki** [comment]
Not a link to image, LGTM though

**Comment by YanaPlotnyk** [comment]
https://github.com/YanaPlotnyk/kottans-js-2016/blob/master/gitbranching.jpg - is that better?

**Comment by sudodoki** [comment]
LGTM
