### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [YanaPlotnyk/kottans-js-2016#2]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить

`````` html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```
``````

**Comment by YanaPlotnyk** [comment]
kottans-js-2016/week01/hw-1.html

**Comment by mkozhukharenko** [comment]
it shouldn't be inside a nav https://github.com/YanaPlotnyk/kottans-js-2016/blob/master/week01/hw-1.html#L40-L44

[read move about  a nav](http://html5doctor.com/nav-element/)

**Comment by mkozhukharenko** [comment]
try to use a figure for this https://github.com/YanaPlotnyk/kottans-js-2016/blob/master/week01/hw-1.html#L52

**Comment by mkozhukharenko** [comment]
https://github.com/YanaPlotnyk/kottans-js-2016/blob/master/week01/hw-1.html#L170-L171
what do you think about wrapping this by nav?

**Comment by mkozhukharenko** [comment]
looks good! 👍
